### ISSUE TITLE
[Bug]: Syntax - Pug - Multi-line Comments Broken

### ISSUE THREAD

**Issue by thecodechef** [thecodechef/sublime-pug-extended#1]
# Multi-Line Comments are broken

## Expected Behavior

![expected_multiline_unbuffered_comments](https://user-images.githubusercontent.com/5333019/42516468-aa11a76a-8423-11e8-91ad-8c03c785a94b.png)

Text Editor: VS Code

## Actual Behavior

![actual_multiline_unbuffered_comments](https://user-images.githubusercontent.com/5333019/42515969-a1b2f08e-8422-11e8-8232-a15267eae310.png)

Text Editor: Sublime Text 3

**Comment by thecodechef** [comment]
@Changepage @FichteFoll

>
  Would You like to help me update the Pug Extended for Sublime,  as the regular Pug seems to be 
  unmaintained i'm going for sublime-syntax other than tmLanguage i just need help with alot of it
  and who better to help me than one of the creators of pug itself, and one of the people whose been 
  developing for sublime for a long time respectfully

**Comment by FichteFoll** [comment]
I suggest checking out our discord for help with syntax definitions. https://discord.gg/D43Pecu

**Comment by thecodechef** [comment]
Ok will do thanks @FichteFoll
